# Generated by Django 2.0.6 on 2018-08-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundayworkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '学生信息',
            },
        ),
    ]
